import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import { futura } from "./fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body 
        className={`
          ${futura.variable} 
          min-h-[600vh]
          bg-[url('/FondGribouillage.webp')]
          
          bg-contain
          sm:bg-cover
          bg-repeat-y
          
          before:content-['']
          before:absolute
          before:top-0
          before:left-0
          before:w-full
          before:h-full
          
          before:-z-10
          antialiased
        `}
      >
        <Header companyName="VotreEntreprise" />
        <main className="pt-16 relative z-0">
          {children}
        </main>
      </body>
    </html>
  );
}
